# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('easyv2v-example', ['easyv2v'])
    obj.source = 'easyv2v-example.cc'

